title: blog.andrewcudzilo.com(dev)
author:
  name: Andrew Cudzilo
  email: 'andrew.cudzilo@gmail.com'
blog:
  route: ''
metadata:
    description: 'Code, Rambles, Fatherhood'
taxonomies: [category,tag,month]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1

